# Generated by Django 5.2.11 on 2026-08-24

import uuid

from django.db import migrations

import tracks.fields


def rewrite_uuid_storage(apps, schema_editor):
    Track = apps.get_model("tracks", "Track")
    DatasetRelease = apps.get_model("tracks", "DatasetRelease")

    track_batch = list(Track.objects.all().iterator(chunk_size=1000))
    if track_batch:
        Track.objects.bulk_update(track_batch, ["track_id", "dataset_id", "genome_id"], batch_size=1000)

    release_batch = list(DatasetRelease.objects.all().iterator(chunk_size=1000))
    if release_batch:
        DatasetRelease.objects.bulk_update(release_batch, ["dataset_id", "genome_id"], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetrelease",
            name="dataset_id",
            field=tracks.fields.HyphenatedUUIDField(),
        ),
        migrations.AlterField(
            model_name="datasetrelease",
            name="genome_id",
            field=tracks.fields.HyphenatedUUIDField(),
        ),
        migrations.AlterField(
            model_name="track",
            name="dataset_id",
            field=tracks.fields.HyphenatedUUIDField(),
        ),
        migrations.AlterField(
            model_name="track",
            name="genome_id",
            field=tracks.fields.HyphenatedUUIDField(),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_id",
            field=tracks.fields.HyphenatedUUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(rewrite_uuid_storage, migrations.RunPython.noop),
    ]
