# Generated by Django 4.1.11 on 2023-10-24 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorytype",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RemoveField(
            model_name="category",
            name="genome",
        ),
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[
                    ("Genomic", "Genomic"),
                    ("Variation", "Variation"),
                    ("Regulation", "Regulation"),
                ],
                default="Genomic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="genome_id",
            field=models.UUIDField(default="a7335667-93e7-11ec-a39d-005056b38ce3"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="label",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="track_category_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="track",
            name="additional_info",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="track",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="tracks.category",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="colour",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="track",
            name="label",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="type",
            field=models.CharField(
                choices=[
                    ("gene", "Gene"),
                    ("variant", "Variant"),
                    ("regular", "Regular"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("name", "url"), name="unique_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("genome_id", "label", "additional_info", "datafiles"),
                name="unique_track",
            ),
        ),
        migrations.DeleteModel(
            name="CategoryType",
        ),
        migrations.DeleteModel(
            name="Genome",
        ),
    ]
