# Generated by Django 4.1.11 on 2024-08-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="track",
            name="display_order",
            field=models.IntegerField(default=2000),
        ),
    ]
