# Generated by Django 4.1.11 on 2024-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0002_track_settings_alter_track_display_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
