# Generated by Django 4.1.11 on 2023-11-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0002_remove_categorytype_category_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={"ordering": ["display_order"]},
        ),
    ]
