# Generated by Django 5.2.1 on 2025-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_remove_track_unique_track_track_dataset_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='release',
            field=models.CharField(default='YYYY-MM', max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='dataset_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
