#Environment variables for Track API k8s deployment
apiVersion: v1
data:
  #Django settings
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECRET_KEY: <DJANGO_SECRET_KEY>
  #DJANGO_DEBUG: "True"
  #Database access (filled & applied manually)
  DATABASE_HOST: ensweb-trackapi-db-svc
  DATABASE_PORT: "5432"
  DATABASE_USER: <DATABASE_USER>
  DATABASE_PASS: <DATABASE_PASS>
  DATABASE_NAME: <DATABASE_NAME>
kind: ConfigMap
metadata:
  name: ensembl-track-api-configmap