genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - gc
type: regular
label: "%GC"
display_order: 900
on_by_default: false
description: Shows the percentage of Gs and Cs in a region
datafiles:
  gc: gc.bb
