genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - contig
type: regular
label: Reference sequence
display_order: 0
on_by_default: true
description: Displays the sequence underlying the assembly