genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
settings:
  repeat-details:
    scales: [1, 8, 2]
  repeat-summary:
    scales: [9, 100, 4]
type: regular
label: "Repeats: RepeatMasker"
additional_info: nrplants
display_order: 615
on_by_default: false
description: Shows repeats detected using RepeatMasker to scan non-redundant elements from several plant libraries, including REdat, TREP and RepetDB among others
sources:
  - name: RepeatMasker
    url: https://www.repeatmasker.org
  - name: REdat
    url: https://mips.helmholtz-muenchen.de/plant/recat
  - name: TREP
    url: https://trep-db.uzh.ch
  - name: RepetDB
    url: https://urgi.versailles.inra.fr/repetdb/begin.do
datafiles:
  repeat-details: repeats.repeatmask_nrplants.bb
  repeat-summary: ""
