genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
settings:
  repeat-details:
    scales: [1, 8, 2]
  repeat-summary:
    scales: [9, 100, 4]
type: regular
label: "Repeats: Centromere"
display_order: 640
on_by_default: false
description: Centromere genomic locations defined by the Genome Reference Consortium
sources:
  - name: Genome Reference Consortium
    url: https://genomereference.org
datafiles:
  repeat-details: repeats.centromere_repeat.bb
  repeat-summary: ""
