genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
settings:
  repeat-details:
    scales: [1, 8, 2]
  repeat-summary:
    scales: [9, 100, 4]
type: regular
label: "Repeats: RED"
additional_info: Annotated
display_order: 671
on_by_default: false
description: Shows repeat regions on the genome, identified by RED (REpeatDetector) and annotated by alignment to a repeat library
sources:
  - name: RED
    url: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0654-5
datafiles:
  repeat-details: repeats.repeatdetector_annotated.bb
  repeat-summary: ""
