genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
settings:
  repeat-details:
    scales: [1, 8, 2]
  repeat-summary:
    scales: [9, 100, 4]
type: regular
label: "Repeats: TRF"
display_order: 660
on_by_default: false
description: Shows repeat regions on the genome, identified by Tandem Repeats Finder
sources:
  - name: Tandem Repeats Finder
    url: https://tandem.bu.edu/trf/trf.html
datafiles:
  repeat-details: repeats.trf.bb
  repeat-summary: ""
