genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
settings:
  repeat-details:
    scales: [1, 8, 2]
  repeat-summary:
    scales: [9, 100, 4]
type: regular
label: "Repeats: ENA"
display_order: 980
on_by_default: true
description: Shows repeat regions annotated in ENA
sources:
  - name: ENA
    url: https://www.ebi.ac.uk/ena
datafiles:
  repeat-details: repeats.ena_repeat.bb
  repeat-summary: ""
