genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
settings:
  repeat-details:
    scales: [1, 8, 2]
  repeat-summary:
    scales: [9, 100, 4]
type: regular
label: "Repeats: Segmental Duplication"
display_order: 680
on_by_default: false
description: Shows regions of segmental duplication. Segmental duplications are long (>1kb) stretches of DNA which are present at more than one location in the genome, sharing a high degree of similarity (>90%).
sources:
  - name: Human Pangenome Reference Consortium
    url: https://humanpangenome.org/
datafiles:
  repeat-details: repeats.segdups.bb
  repeat-summary: ""
