genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
settings:
  repeat-details:
    scales: [1, 8, 2]
  repeat-summary:
    scales: [9, 100, 4]
type: regular
label: "Low complexity: Pombase"
display_order: 986
on_by_default: true
description: Low complexity region simple features annotated by PomBase and imported into Ensembl
sources:
  - name: PomBase
    url: https://www.pombase.org
datafiles:
  repeat-details: repeats.low_complexity_region.bb
  repeat-summary: ""
