genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
settings:
  repeat-details:
    scales: [1, 8, 2]
  repeat-summary:
    scales: [9, 100, 4]
type: regular
label: "Repeats: Repeatmasker"
display_order: 980
on_by_default: false
description: Shows repeat regions on the genome, identified by RepeatMasker using a RepBase, or custom generated repeat library
sources:
  - name: RepeatMasker
    url: https://www.repeatmasker.org
datafiles:
  repeat-details: repeats.repeatmask.bb
  repeat-summary: ""
