genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
settings:
  repeat-details:
    scales: [1, 8, 2]
  repeat-summary:
    scales: [9, 100, 4]
type: regular
label: "Repeats: Segmental Duplication"
display_order: 650
on_by_default: false
description: Shows segmental duplication regions, defined as large low-copy repeats with a high degree of sequence similarity that can be either intra- or inter-chromosomal. 
sources:
  - name: Human Pangenome Reference Consortium
    url: https://humanpangenome.org/
datafiles:
  repeat-details: repeats.segdups.bb
  repeat-summary: ""
