genome_id: <genome_id>
category:
  track_category_id: assembly
  label: Assembly
  type: Genomic
trigger:
  - track
  - expand
type: regular
label: CpG islands
display_order: 971
on_by_default: true
description: |-
  Displays CpG islands - regions of nucleic acid sequence containing a high number of adjacent cytosine-guanine pairs (along one strand). 
  Usually unmethylated, they are associated with promoters and regulatory regions. 
  They are determined from the genomic sequence using a program written by G. Micklem, similar to newcpgreport in the EMBOSS package.
sources:
  - name: newcpgreport
    url: https://emboss.sourceforge.net/apps/cvs/emboss/apps/newcpgreport.html
datafiles:
  cpg: simple-features.bb
