genome_id: <genome_id>
category:
  track_category_id: genes-transcripts
  label: Genes & transcripts
  type: Genomic
trigger:
  - track
  - gene-pc-fwd
type: gene
label: Protein coding genes
additional_info: Forward strand
colour: DARK_GREY
display_order: -110
on_by_default: true
description: Shows all protein coding genes on the forward strand.
datafiles:
  gene: transcripts.bb
