genome_id: <genome_id>
category:
  track_category_id: genes-transcripts
  label: Genes & transcripts
  type: Genomic
trigger:
  - track
  - gene-pc-rev
type: gene
label: Protein coding genes
additional_info: Reverse strand
colour: DARK_GREY
display_order: 100
on_by_default: true
description: Shows all protein coding genes on the reverse strand.
datafiles:
  gene: transcripts.bb
