genome_id: <genome_id>
category:
  track_category_id: short-variants
  label: Short variants by resource
  type: Variation
trigger:
  - track
  - expand
settings:
  variant-details:
    switches:
      - label-snv-id
      - label-snv-alleles
      - label-other-id
      - label-other-alleles
      - show-extents
type: variant
label: Ensembl short variants
display_order: 1001
on_by_default: true
description: All short variants (SNPs and indel) data from Ensembl - e110
sources:
  - name: Ensembl
    url: https://www.ensembl.org/index.html
datafiles:
  variant-details: variant-ensembl-details.bb
  variant-summary: variant-ensembl-summary.bw
