genome_id: <genome_id>
category:
  track_category_id: short-variants
  label: Short variants by resource
  type: Variation
trigger:
  - track
  - expand-variation
settings:
  variant-details:
    switches:
      - label-snv-id
      - label-snv-alleles
      - label-other-id
      - label-other-alleles
      - show-extents
type: variant
label: dbSNP short variants
display_order: 1000
on_by_default: true
description: All short variants (SNPs and indels) data from dbSNP - build 156
sources:
  - name: dbSNP
    url: https://www.ncbi.nlm.nih.gov/snp
datafiles:
  variant-details: variant-dbsnp-details.bb
  variant-summary: variant-dbsnp-summary.bw
